<?php
/**
 * @file
 * Main module file for the openlayers_osmbuildngs module.
 */

require_once('openlayers_osmbuildings.inc');


/**
 * Implements hook_ctools_plugins_api().
 */
function olob_ctools_plugin_api($module, $api) {
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_maps':
      case 'openlayers_layers':
        return array('version' => 1);
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function olob_ctools_plugin_directory($module, $plugin) {
  if ($module == 'openlayers' && !empty($plugin)) {
    return 'includes/' . $plugin;
  }
}

/**
 * Implements hook_libraries_infos().
 */
function olob_libraries_info() {
  $libraries = array();
  $libraries['osmbuildings'] = array(
    'name' => 'OSMBuildings',
    'vendor url' => 'https://github.com/kekscom/osmbuildings/',
    'download url' => 'https://raw.githubusercontent.com/kekscom/osmbuildings/master/dist/OSMBuildings-OpenLayers.js',
    'library path' => _olob_get_path(),
    'version' => '0.2.1b',
    'files' => array(
      'js' => array('OSMBuildings-OpenLayers.js'),
    ),
    'dependencies' => array(
      'openlayers'
    ),
  );

  return $libraries;
}

/**
 * Implements hook_openlayers_layer_types().
 */
function olob_openlayers_layer_types() {
  $layers['openlayers_layer_type_osmbuildings'] = array(
    'title' => t('OSM Buildings'),
    'description' => t('Provide 3d map layer'),
    'path' => drupal_get_path('module', 'olob') . '/includes/layer_types',
    'layer_type' => array(
      'file' => 'openlayers_layer_type_osmbuildings.inc',
      'class' => 'openlayers_layer_type_osmbuildings',
      'parent' => 'openlayers_layer_type',
    ),
  );

  return $layers;
}

/**
 * Return path to library.
 *
 * Return the path to the default bundled library if not found in
 * sites/all/libraries.
 *
 * @return string
 */
function _olob_get_path() {
  $lib = libraries_get_libraries();

  if (isset($lib['osmbuildings'])) {
    if (file_exists($lib['osmbuildings'])) {
      return $lib['osmbuildings'];
    }
  }

  return drupal_get_path('module', 'olob') . '/lib/osmbuildings';
}
